---
title: "Time Analysis of Bikeshare Data"
author: "Lucas Adams"
date: "2023-10-23"
output: pdf_document
---
# Loading packages
```{r}
library(tidyverse)
library(here)
library(janitor)
```

# Loading data
```{r}
df1 <- read_csv(here("data_raw", "202309-capitalbikeshare-tripdata.csv"))
```

# Creating new dataframe that only looks at first 100 observations
```{r}
df2 = df1 %>%
  slice(1:1000)
```

# Combining timestamps into one column
```{r}
df3 = pivot_longer(df2, cols = c("started_at", "ended_at"), values_to = "time")
```

# New Variable for Start and End
```{r}
df3 = df3 %>%
  mutate(time_type = case_when(
  time %in% df2$started_at ~ "start",       
  time %in% df2$ended_at ~ "end",       
  ))
```

# Sorting timestamps
```{r}
df3 = df3 %>%
  arrange(time)
```

# Assigning value to start and end for cumulative sum calc later
```{r}
df4 = df3 %>%
  mutate(up_down = case_when(
  time_type == "start" ~ 1,
  time_type == "end" ~ -1
  ))
```

# Creating cumulative sum variable
```{r}
df5 = df4 %>%
  mutate(riders = cumsum(up_down))
```

# Plotting time vs number of riders
```{r}
ggplot(df5, aes(x = time, y = riders)) + geom_line()
```

